#ifndef HEAPED_H
#define HEAPED_H

// This file is auto-generated by cbindgen. Do not edit.

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

#endif  /* HEAPED_H */
